name: Lint

"on":
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint-github-action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: .github/workflows/
          yamllint_config_filepath: .github/.yamllint
