name: Lint

"on":
  push:
    branches-ignore:
      - main
    tags:
      - *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2-action@v17
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: '**/*.md'
      - name: Run create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          author: >-
            github-actions[bot]
            <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "fix: Lint suggestions"
          branch: "patch/${{ github.ref_name }}"
          title: "fix: Lint suggestions for ${{ github.ref_name }}"
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint-github-action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: .
          yamllint_config_filepath: .github/.yamllint

