name: Release

"on":
  create:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  openPR:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v45
        id: updCont
        with:
          files: |
            content/**
            data/**
      - uses: tj-actions/changed-files@v45
        id: updSrc
        with:
          files: |
            *
            !content/**
            !data/**
      - name: Create PR
        if: ${{ github.event_name }} != create
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base "main" \
            --head "${{ github.ref_name }}" \
            --title "Release/${{ github.ref_name }}" \
            --body "" \
            --draft
      - name: Mark as post
        if: steps.updCont.outputs.any_changed == "true"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit --add-label "create post"
      - name: Mark as dev
        if: steps.updSrc.outputs.any_changed == "true"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit --add-label "development"
