name: Release

"on": ["create"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  openPR:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Create PR
        run: |
          gh pr create \
            --base "main" \
            --head "${{ github.ref_name }}" \
            --title "Release/${{ github.ref_name }}" \
            --body "" \
            --draft
